server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.fmr.ec3.oscc.common.serde.EventEnvelopeSerializer

simulation:
  agent-count: 400
  login-percent: 95
  tick-interval-ms: 2000
  heartbeat-interval-ms: 5000
  sip-server-count: 4
  media-server-count: 120
  ivr-tick-interval-ms: 3000

logging:
  level:
    com.fmr.ec3.oscc.sender: DEBUG
